### ISSUE TITLE
Audio Playback

### ISSUE THREAD

**Issue by maverick74** [Blobfolio/js-mate-poe#1]
Please, submit Screen Mate Poe to AMO, so that we can get updates of it :)

**Comment by joshstoik1** [comment]
Thanks for opening the issue, @maverick74!

It took me a few releases to get it right, but Firefox will — or at least _should_ — automatically update JS Mate Poe `1.4.3` and newer, same as any other add-on.

(`1.4.2` and earlier, however, will require one manual update to get them on the same page.)

Do you happen to know which version you had originally installed?

Regarding AMO, I am just waiting for Firefox to finish ironing out its support and documentation for the new "Manifest V3" extension format. (The build/submission/review process for Mozilla-hosted content is extra tedious, so I want to ensure Poe's v2->v3 transition is fully squared away beforehand. :wink:)

**Comment by maverick74** [comment]
Hi!

I just found out about it last friday, so... i only used 1.4.3.
It updates automatically?! Now that's something i didn't know was possible outside of AMO!!! That's great, then!
Problem solved! :+1: 

**Still, AMO will give it a lot more visibility!!!**

I used to run _Screen Mate Poe_ back in the days (late 90's??? Early 2000's?!?!) and i'm sure i still have a copy of it not too far away!!! It was a lot of fun!!!
(i remember i once "filled" a friend's screen until i could not load any more instances of it ahahahaha it was a real screen flock ahahaha - sorry, i could not resist to share this ahahah)

In the meanwhile, i think i found another bug (can fill a new bug report if you wish): I'm on Linux and i don't have any sound.

**Comment by joshstoik1** [comment]
> It updates automatically?! […] Problem solved!

Yep! I'm not sure how often Firefox polls for add-on updates, but you can force it to do so immediately by selecting "Check For Updates" from the Manage Your Extensions settings menu (the gear icon at the top).

> i don't have any sound

Audio became a preference in `1.4.4` — default off — so you might have to enable it first. (You can do that from Poe's Preferences tab on the Manage Your Extensions page.)

But beyond that, Firefox (like pretty much every other browser) suppresses auto-playing audio until you have clicked somewhere (anywhere) on the page. (That interaction symbolizes "consent", I guess?) Sounds coming from browser extensions like Poe, unfortunately, aren't treated any differently.

As far as I'm aware, there isn't any way around it. You just have to click something each time you load a new page. :shrug: 

> (i remember i once "filled" a friend's screen until i could not load any more instances of it ahahahaha it was a real screen flock ahahaha - sorry, i could not resist to share this ahahah)

Poe was a permanent fixture of my desktop from Windows 3.1 all the way up to XP, until that fateful day in 2005 when Microsoft finally dropped support for 16-bit applications. :cry:

**Comment by maverick74** [comment]
> You can do that from Poe's Preferences tab on the Manage Your Extensions page.)

That was the first thing I done but it didn't work. I'll try clicking on the page, maybe that's what I missed...

**Comment by maverick74** [comment]
no... even in clicking on the page! i don't get any sound no matter what i do

> Poe was a permanent fixture of my desktop from Windows 3.1 all the way up to XP

Not all the time but i think i used it from 95 until XP
(never used 3.1 and 95 was just at work. At home i went strait from my good old speccy to 98se eheh)

**Comment by joshstoik1** [comment]
> no... even in clicking on the page! i don't get any sound no matter what i do

Animation sequences with audio have a very low probability of occurring, so this could be tricky to debug. The quickest pathway to sound is through the `BigFish` entrance animation, where Poe runs in from the right and is gobbled up by a larger Poe a few seconds later. After popping back up, there is a roughly 1/3 chance he'll `Sneeze` (otherwise he'll just `Walk`).

When Firefox can't play a sound for whatever reason, it should print a warning or error to the console explaining why.

With that in mind:
1. Go to a fairly quiet page, like https://duckduckgo.com/, and open the browser's console pane (SHIFT+CTRL+K on Linux), making sure the `Error` and `Warning` tabs are enabled.
2. Double-click some random text on the page get the "interaction" out of the way.
3. Toggle the Poe extension off/on by clicking the URL bar icon until it loads the `BigFish` sequence then wait to see if that leads to a `Sneeze`. If it doesn't, rinse and repeat.

If you don't hear any sound during the `Sneeze`, take a look at the console to see if any new error or warning messages appeared, and copy-and-paste those here!

Thank you for all of the back-and-forth, by the way! I really appreciate you taking the time.

**Comment by maverick74** [comment]
OK. I can confirm it does have sound!!!

I'm terribly sorry for wasting your time in two issues where there actually was no issue.

My bad!!!

My problem was that i had idea that this sequence:

![imagem](https://user-images.githubusercontent.com/14912461/233038612-93022105-69e5-497e-833c-70dc77488fa4.png)

had a "me-e-e-ehh" (or ba-a-a-a-hhh) after :p

**Comment by maverick74** [comment]
> It _feels_ about right, I think, but JS Mate Poe is definitely not a shot-for-shot remake. wink

That explains it!!!

I thought it was a remake from the original sources or, even, some reverse-engineering / de-compilation of the original.

(would be nice to have the original author on board and his blessing)
